version: "3"

services:
  api:
    build: ./api
    ports:
      - "${API_INTERNAL_PORT}:${API_EXTERNAL_PORT}"
    environment:
      - API_PORT=${API_INTERNAL_PORT}
      - DB_PORT=${DB_EXTERNAL_PORT}
      - DB_USER=${DB_API_USER}
      - DB_PASS=${DB_API_PASS}
      - DB_AUTH_SOURCE=${DB_AUTH_SOURCE}
      - WAIT_HOSTS=db:${DB_EXTERNAL_PORT}
    working_dir: /app
    volumes:
      - ./api:/app

  db:
    build: ./db
    ports:
      - "${DB_INTERNAL_PORT}:${DB_EXTERNAL_PORT}"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${DB_ADMIN_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${DB_ADMIN_PASS}
      - DB_API_USER=${DB_API_USER}
      - DB_API_PASS=${DB_API_PASS}
    volumes:
      - ./db/db-init.js:/docker-entrypoint-initdb.d/db-init.js:ro
      - db:/app

volumes:
  db:
